name: Playwright Tests

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install system dependencies (Ubuntu 24.04 compatible)
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libasound2t64 \  # Замена для libasound2
          libatk1.0-0 \
          libatk-bridge2.0-0 \
          libcups2 \
          libdbus-1-3 \
          libdrm2 \
          libgbm1 \
          libglib2.0-0 \
          libnspr4 \
          libnss3 \
          libpango-1.0-0 \
          libx11-6 \
          libxcb1 \
          libxcomposite1 \
          libxdamage1 \
          libxext6 \
          libxfixes3 \
          libxrandr2 \
          libxshmfence1 \
          libxtst6 \
          libffi8 \  # Замена для libffi7
          x264 \    # Замена для libx264-163
          libvpx7 \
          libopus0

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-playwright

    - name: Install Playwright with browsers
      run: |
        playwright install --with-deps chromium
        playwright install-deps

    - name: Run tests
      run: |
        pytest